name: Go Coverage Badge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Test with coverage
      run: go test ./... -coverprofile=coverage.out

    - name: Go Coverage Badge
      uses: tj-actions/coverage-badge-go@v2
      with:
        path: ./coverage.out
        readme-path: ./README.md # Adjust if your README is located elsewhere
